### ISSUE TITLE
Concept from pandas dataframe

### ISSUE THREAD

**Issue by Mataivic** [xflr6/concepts#3]
Hello,

Have you consider to allow the creation of a formal context based on a pandas DataFrame, which could be a sparse matrix (with empty cells and cells filled with 'X' or 1) or a binary matrix (filled with 0/1) ?

In my current work, I use a pandas dataframe filled with 'X' and blank cells, as needed by the package, but I have to export the file in a csv file before re-opening it with the concepts.Context.fromfile() method, which is not practical.

Thanks.

**Comment by xflr6** [comment]
Thanks. I think this would rather be something for a recipe, because there might be too many possible options in terms of data types and coding in the pandas dataframe. But I think this is a quick one:

```python
import concepts
import pandas as pd

CONTEXT = 'examples/relations.csv'

c = concepts.load_csv(CONTEXT)

df = pd.read_csv(CONTEXT, index_col='name')
objects = df.index.tolist()
properties = list(df)
bools = [[False if v is pd.np.nan else bool(v) for v in r] for _, r in df.iterrows()]

c_ = concepts.Context(objects, properties, bools)
assert c_ == c
```

**Comment by xflr6** [comment]
Maybe more efficient:
```python
bools = list(df.fillna(False).astype(bool).itertuples(index=False, name=None))
```
